# Generated by Django 5.0.1 on 2024-02-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='due_date',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
